### ISSUE TITLE
Not Compatible with Dark Desktop Theme

### ISSUE THREAD

**Issue by jjelev** [rabadiw/onemark#1]
Not working well on dark desktop theme. I use KDE with Breeze Dark and black fonts are displayed on a black menu. The only way to see what you are selecting is to highlight the menu options until you find the one you want.

**Comment by rabadiw** [comment]
Thanks for the feedback and thanks for trying the App. Certainly will be on the list of to-dos.

**Comment by rabadiw** [comment]
It's been a while, but resolved!
